### ISSUE TITLE
wawooow！ 

### ISSUE THREAD

**Issue by nickChenyx** [lazzzis/LeetCode#1]
看你最近的提交图，代码提交很勤快啊。
想看看你的 **leetcode 刷了哪些** ，结果你竟然一个问题一个文件夹... 
这个检索起来实在是太不方便了，补充一个README，并且在里面用标签做索引吧，索引名就是题目名。
这样看起来好找一点。

**Comment by lazzzis** [comment]
索引这个建议挺不错的，所以我按你说的补了一个 README

不过一个问题一个文件夹这个是我有意为之的，因为我一个题下可能有多个文件 -- 代表多种解题方式
